project_id = "fezjiutlszkrvdubfvnc"

[functions.submit-assessment-v2]
verify_jwt = false

[functions.send-application-notification]
verify_jwt = false

[functions.send-assessment]
verify_jwt = false

[functions.generate-ai-evaluation]
verify_jwt = false

[functions.generate-interview-questions]
verify_jwt = false

[functions.send-weekly-report]
verify_jwt = false

[functions.send-assessment-confirmation]
verify_jwt = false

[functions.submit-assessment]
verify_jwt = false
